/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author jcamelo
 */
public class ConversorMoeda extends javax.swing.JFrame {

    /**
     * Creates new form ConversorMoeda
     */
    public ConversorMoeda() {
        initComponents();
  
    }
    
    public String converter(String moeda1, String moeda2, Double valor){
        
        NumberFormat real = NumberFormat.getCurrencyInstance(new Locale("pt","BR"));
        NumberFormat dolar = NumberFormat.getCurrencyInstance(new Locale("en","US"));
        NumberFormat euro = NumberFormat.getCurrencyInstance(new Locale("pt","PT"));
        NumberFormat dolarCA = NumberFormat.getCurrencyInstance(new Locale("en","CA"));
        NumberFormat libra = NumberFormat.getCurrencyInstance(new Locale("en","GB"));
        
        
        if(moeda1.equals("Real")){
            if(moeda2.equals("Dólar US"))
                return real.format(valor)+" = "+dolar.format(valor*0.19);
            if(moeda2.equals("Euro"))
                return real.format(valor)+" = "+euro.format(valor*0.18);
            if(moeda2.equals("Dólar CAD"))
                return real.format(valor)+" = "+dolarCA.format(valor*0.25);
            if(moeda2.equals("Libra Esterlina"))
                return real.format(valor)+" = "+libra.format(valor*0.16); 
        }
        if(moeda1.equals("Dólar US")){
            if(moeda2.equals("Real"))
                return dolar.format(valor)+" = "+real.format(valor*5.23);
            if(moeda2.equals("Euro"))
                return dolar.format(valor)+" = "+euro.format(valor*0.94);
            if(moeda2.equals("Dólar CAD"))
                return dolar.format(valor)+" = "+dolarCA.format(valor*1.29);
            if(moeda2.equals("Libra Esterlina"))
                return dolar.format(valor)+" = "+libra.format(valor*0.81);
        }
        if(moeda1.equals("Euro")){
            if(moeda2.equals("Real"))
                return euro.format(valor) + " = "+real.format(valor*5.53);
            if(moeda2.equals("Dólar US"))
                return euro.format(valor) + " = "+dolar.format(valor*1.06);
            if(moeda2.equals("Dólar CAD"))
                return euro.format(valor) + " = "+dolarCA.format(valor*1.36);
            if(moeda2.equals("Libra Esterlina"))
                return euro.format(valor)+" = "+libra.format(valor*0.86);
        }
        if(moeda1.equals("Dólar CAD")){
            if(moeda2.equals("Real"))
                return dolarCA.format(valor) + " = "+real.format(valor*4.06);
            if(moeda2.equals("Dólar US"))
                return dolarCA.format(valor) + " = "+dolar.format(valor*0.78);
            if(moeda2.equals("Euro"))
                return dolarCA.format(valor) + " = "+euro.format(valor*0.73);
            if(moeda2.equals("Libra Esterlina"))
                return dolarCA.format(valor)+" = "+libra.format(valor*0.63);
        }
        if(moeda1.equals("Libra Esterlina")){
            if(moeda2.equals("Real"))
                return libra.format(valor) + " = "+real.format(valor*6.42);
            if(moeda2.equals("Dólar US"))
                return libra.format(valor) + " = "+dolar.format(valor*1.23);
            if(moeda2.equals("Euro"))
                return libra.format(valor) + " = "+euro.format(valor*1.16);
            if(moeda2.equals("Dólar CAD"))
                return libra.format(valor)+" = "+dolarCA.format(valor*1.58);
        }
        
        return "";       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboMoeda1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboMoeda2 = new javax.swing.JComboBox<>();
        btnConverter = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lbValorConvertido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JWConversor Moeda");

        jLabel1.setText("Valor");

        txtValor.setText("1");

        jLabel2.setText("Converter de");

        comboMoeda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a moeda", "Real", "Euro", "Dólar US", "Dólar CAD", "Libra Esterlina" }));

        jLabel3.setText("Converter para");

        comboMoeda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a moeda", "Real", "Euro", "Dólar US", "Dólar CAD", "Libra Esterlina" }));

        btnConverter.setText("Converter");
        btnConverter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lbValorConvertido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbValorConvertido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorConvertido.setText("Valor Convertido");
        lbValorConvertido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbValorConvertido.setPreferredSize(new java.awt.Dimension(300, 20));
        lbValorConvertido.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbValorConvertidoPropertyChange(evt);
            }
        });

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboMoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(lbValorConvertido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConverter)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConverter)
                    .addComponent(btnLimpar)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(lbValorConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtValor.setText("1");
        comboMoeda1.setSelectedIndex(0);
        comboMoeda2.setSelectedIndex(0);
        lbValorConvertido.setText("Valor Convertido");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        if(comboMoeda1.getSelectedIndex()==0 || comboMoeda2.getSelectedIndex() == 0)
            JOptionPane.showMessageDialog(null,"Selecione a moeda para conversão!","Moeda não selecionada",1);
        else
            if(comboMoeda1.getSelectedIndex() == comboMoeda2.getSelectedIndex())
                JOptionPane.showMessageDialog(null,"As moedas selecionadas são iguais!","Moedas selecionadas iguais",1);
            else
                lbValorConvertido.setText(converter(comboMoeda1.getSelectedItem().toString(),comboMoeda2.getSelectedItem().toString(),Double.parseDouble(txtValor.getText().replace(",", "."))));
            
        
    }//GEN-LAST:event_btnConverterActionPerformed

    private void lbValorConvertidoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbValorConvertidoPropertyChange
        
    }//GEN-LAST:event_lbValorConvertidoPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.dispose();
         Inicio inicio = new Inicio();
         inicio.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverter;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> comboMoeda1;
    private javax.swing.JComboBox<String> comboMoeda2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbValorConvertido;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
