/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author jcamelo
 */
public class ConversorTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConversorMoeda
     */
    public ConversorTemperatura() {
        initComponents();

    }

    public String converter(String temp1, String temp2, Double valor) {
        DecimalFormat decimal = new DecimalFormat("#,##0.00");

        if (temp1.equals("Celsius (°C)")) {
            if (temp2.equals("Fahrenheit (°F)")) {
                return decimal.format(valor * 9 / 5 + 32) + " °F";
            }
            if (temp2.equals("Kelvin (K)")) {
                return decimal.format(valor + 273.15) + " K";
            }
        }
        if (temp1.equals("Fahrenheit (°F)")) {
            if (temp2.equals("Celsius (°C)")) {
                return decimal.format((valor - 32) * 5 / 9) + "(°C)";
            }
            if (temp2.equals("Kelvin (K)")) {
                return decimal.format((valor - 32) * 5 / 9 + 273.15) + " K";
            }

        }
        if (temp1.equals("Kelvin (K)")) {
            if (temp2.equals("Fahrenheit (°F)")) {
                return decimal.format((valor - 273.15) * 9 / 5 + 32) + " °F";
            }
            if (temp2.equals("Celsius (°C)")) {
                return decimal.format(valor - 273.15) + "°C";
            }

        }

        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTemp1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboTemp2 = new javax.swing.JComboBox<>();
        btnConverter = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lbValorConvertido = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JWConversor Temperatura");

        jLabel1.setText("Temperatura");

        txtValor.setText("1");

        jLabel2.setText("Converter de");

        comboTemp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a unidade", "Celsius (°C)", "Fahrenheit (°F)", "Kelvin (K)" }));

        jLabel3.setText("Converter para");

        comboTemp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a unidade", "Celsius (°C)", "Fahrenheit (°F)", "Kelvin (K)" }));

        btnConverter.setText("Converter");
        btnConverter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverterActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lbValorConvertido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbValorConvertido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbValorConvertido.setText("Valor Convertido");
        lbValorConvertido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbValorConvertido.setPreferredSize(new java.awt.Dimension(300, 20));
        lbValorConvertido.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbValorConvertidoPropertyChange(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbValorConvertido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(comboTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnConverter)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConverter)
                    .addComponent(btnLimpar)
                    .addComponent(btnVoltar))
                .addGap(31, 31, 31)
                .addComponent(lbValorConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtValor.setText("1");
        comboTemp1.setSelectedIndex(0);
        comboTemp2.setSelectedIndex(0);
        lbValorConvertido.setText("Valor Convertido");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverterActionPerformed
        if (comboTemp1.getSelectedIndex() == 0 || comboTemp2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione a unidade para conversão!", "Unidade de temperatura não selecionada", 1);
        } else if (comboTemp1.getSelectedIndex() == comboTemp2.getSelectedIndex()) {
            JOptionPane.showMessageDialog(null, "As unidades selecionadas são iguais!", "Moedas selecionadas iguais", 1);
        } else {
            lbValorConvertido.setText(converter(comboTemp1.getSelectedItem().toString(), comboTemp2.getSelectedItem().toString(), Double.parseDouble(txtValor.getText().replace(",", "."))));
        }


    }//GEN-LAST:event_btnConverterActionPerformed

    private void lbValorConvertidoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbValorConvertidoPropertyChange

    }//GEN-LAST:event_lbValorConvertidoPropertyChange

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
         this.dispose();
         Inicio inicio = new Inicio();
         inicio.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverter;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboTemp1;
    private javax.swing.JComboBox<String> comboTemp2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbValorConvertido;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
